## 1. Intro
The NumPy library is the core library for scientific computing in  Python. It provides a high-performance multidimensional array  object, and tools for working with these arrays. 
<br/> Use the following import convention:
```Python
import numpy as np
```

<img src="./Screenshots/NumPy_01.PNG">

<img src="./Screenshots/NumPy_02.jpg">

3D array:
<br/>https://stackoverflow.com/questions/22981845/3-dimensional-array-in-numpy

## 2. Creating Arrays

In [28]:
import numpy as np

a = np.array([1, 2, 3]) #1D array
a

array([1, 2, 3])

In [29]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float) # 2D array

In [31]:
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], 
             dtype = float) # 3D array
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### Initial Placeholders

In [12]:
# Create an array of zeros with 3 rows, 4 columns
np.zeros((3, 4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# Create an array of zeros with 2 depths, 3 rows, 4 columns
np.zeros((2, 3, 4)) 

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
# Create an array of ones with 2 depths, 3 rows, 4 columns, int16-type number
d = np.ones((2, 3, 4), dtype = np.int16)
d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [15]:
# Create an array of evenly spaced values (step value):
# from 10 to <25 with step = 3 => there is not 25 value.
np.arange(10, 25, 3)

array([10, 13, 16, 19, 22])

In [17]:
# Create an array of evenly spaced values (number of samples):
# from 0 to 2 with 9 values 
# => step = 2 / (9-1) = 0.25
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [19]:
# Create a constant array:
# 2 rows, 3 colums, all values = 7
e = np.full((2, 3), 7)
e

array([[7, 7, 7],
       [7, 7, 7]])

In linear algebra, the **`identity matrix`**, or sometimes ambiguously called a **unit matrix**, of size n is the n × n square matrix with **ones on the main diagonal** and **zeros elsewhere**.

In [22]:
# Create a 2X2 identity matrix
f = np.eye(2, dtype = np.int16)
f

array([[1, 0],
       [0, 1]], dtype=int16)

In [24]:
# Create an array with random values: 2 rows, 3 colums
np.random.random((2, 3))  

array([[0.58033971, 0.9148345 , 0.64545466],
       [0.53253157, 0.21849877, 0.96752206]])

In [25]:
# Create an empty array
# Return a new array of given shape and type, 
# without initializing entries.
np.empty((3, 4))  

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3. I/O

### Saving & Loading On Disk

In [36]:
np.save('my_array', a)

In [37]:
# numpy.savez(file, *args, **kwds)
# Save several arrays into a single file in uncompressed .npz format.
np.savez('array.npz', a, b)

In [38]:
np.load('my_array.npy')

array([1, 2, 3])

In [39]:
np.load('array.npz')

### Saving & Loading Text Files

```Python
np.loadtxt("myfile.txt")
np.genfromtxt("my_file.csv", delimiter=',')
np.savetxt("myarray.txt", a, delimiter=" ")
```

## 4. Data Types

- **np.intZZ**: Signed ZZ-bit integer types (ZZ = 16, 32, 64, default int32)
- **np.float32**: Standard double-precision floating point
- **np.complex**: Complex numbers represented by 128 floats
- **np.bool**: Boolean type storing TRUE and FALSE values
- **np.object**: Python object type
- **np.string_**: Fixed-length string type
- **np.unicode_**: Fixed-length unicode type

## 5 . Inspecting Your Array

In [51]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], 
                 dtype = float)

### Array dimensions

In [45]:
a.shape

(3,)

In [46]:
b.shape # show row, columm

(2, 3)

In [47]:
c.shape # show depth, row, column

(2, 2, 3)

### Length of array: 
Return first dimension, in 3D -> show depth

In [48]:
len(a)

3

In [49]:
len(b)

2

In [50]:
len(c)

2

In [58]:
c_test = np.array([[(1.5, 2, 3), (4, 5, 6)], 
              [(3, 2, 1), (4, 5, 6)], 
              [(3, 2, 1), (4, 5, 6)]])
c_test

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [61]:
c_test.shape

(3, 2, 3)

In [55]:
len(c_test)

3

### Number of array dimensions

In [62]:
a.ndim

1

In [63]:
b.ndim

2

In [64]:
c.ndim

3

### Data type of array elements

In [65]:
a.dtype

dtype('int32')

In [66]:
b.dtype

dtype('float64')

In [67]:
c.dtype

dtype('float64')

### Name of data type

In [68]:
a.dtype.name

'int32'

In [69]:
b.dtype.name

'float64'

In [70]:
c.dtype.name

'float64'

### Convert an array to a different type

In [71]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
c.astype(int)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [4, 5, 6]]])

## 6. Asking For Help

In [73]:
 np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## 7. Array Mathematics

### Arithmetic Operations

In [74]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)

In [76]:
# Subtraction
# a will be converted to ([1, 2, 3], [1, 2, 3]) before being substracted
g = a - b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [77]:
np.subtract(a, b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [78]:
# Addition
a + b

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [79]:
np.add(a, b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [80]:
# Division
a / b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [81]:
np.divide(a, b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [82]:
#  Multiplication
a * b  

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [83]:
np.multiply(a, b) 

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [84]:
# Exponentiation
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [85]:
# Square root
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [86]:
# Print sines of an array
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [87]:
# Element-wise cosine
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [90]:
# Element-wise natural logarithm
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In mathematics, the **`dot product`** or **scalar product** is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number.

The dot product of two vectors $a = [a_1, a_2, …, a_n]$ and $b = [b_1, b_2, …, b_n]$ is defined as:
$$a \cdot b = \sum_{i=0}^{n} {a_1b_1 + a_2b_2 + ... + a_nb_n}$$
$$a \cdot b = ab^T$$

In [111]:
# Dot product
d1 = np.array([(2, -3, 6), (3, -3, 2)])
d2 = np.array([4, 5, -1])

d1.dot(d2)
#row1: 2*4 + -3*5 + 6*(-1) = -13
#row2: 3*4 + -3*5 + 2*(-1) = -5

array([-13,  -5])

### Comparison

In [101]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)

In [102]:
a == b  

array([[False,  True,  True],
       [False, False, False]])

In [103]:
a < 2

array([ True, False, False])

In [104]:
np.array_equal(a, b)

False

### Aggregate Functions

In [105]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (6, 1, 5)], dtype = float)

In [106]:
a.sum() 

6

In [107]:
a.min()

1

In [112]:
b.max(axis = 0)

array([6., 2., 5.])

In [109]:
b.max(axis = 1)

array([3., 6.])

In [113]:
# Cumulative sum of the elements
b.cumsum(axis = 0) 

array([[1.5, 2. , 3. ],
       [7.5, 3. , 8. ]])

In [114]:
b.cumsum(axis = 1) 

array([[ 1.5,  3.5,  6.5],
       [ 6. ,  7. , 12. ]])

In [126]:
# Returns the average of the array elements along given axis.
b.mean()
# (1.5 + 2 + 3 +6 + 1 + 5)/6 = b.mean()

3.0833333333333335

In [127]:
b.mean(axis = 0)

array([3.75, 1.5 , 4.  ])

In [128]:
b.mean(axis = 1)

array([2.16666667, 4.        ])

In [132]:
np.median(b)

2.5

In [133]:
# Correlation coefficient
np.corrcoef(a) 

1.0

In [134]:
# Standard deviation
np.std(b)

1.8352262954621033

## 8. Copying Arrays

In [135]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (6, 1, 5)], dtype = float)

In [136]:
# Create a view of the array with the same data
h = a.view() 
h

array([1, 2, 3])

In [137]:
# Create a copy of the array
np.copy(a)

array([1, 2, 3])

In [139]:
# Create a deep copy of the array
h = a.copy()
h

array([1, 2, 3])

**view() vs copy**:
<br/> https://www.jessicayung.com/numpy-views-vs-copies-avoiding-costly-mistakes/
<br/> https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html

In [146]:
Z = np.random.randn(5, 2)
 
Z1 = Z[:3, :]  # view
print(Z1.base is Z)  # True: Z1 is a view.
 
Z2 = Z[[0, 1, 2], :]  # copy
print(Z2.base is Z)  # False: Z2 is a copy. In fact, Z2.base is None.

True
False


#### Views vs Copies: The main differences
Here are the main differences between views and copies:

1. Modifying the array
    - Modifying a view modifies the base (original) array, whereas modifying a copy does not modify the base array.
2. Time taken
    - Making a copy takes more time, often 1.5x-2x longer.
3. Base of the array
    - A view has the same base as its base array. A copy does not.
4. Memory
    - A view also shares memory with the base array, whereas a copy does not.

<img src="./Screenshots/NumPy_03.PNG">

**np.copy() vs `=`**

In [140]:
x = np.array([1, 2, 3])
y = x
y

array([1, 2, 3])

In [141]:
z = np.copy(x)
z

array([1, 2, 3])

Note that, when we modify x, y changes, but not z:

In [142]:
x[0] = 10
x[0] == y[0]

True

In [143]:
x[0] == z[0]

False

**np.copy() vs ndarray.copy()**

https://stackoverflow.com/questions/56028405/difference-between-array-copy-vs-numpy-copyarray

If `a` is a `numpy.array`, the **result will be the same**. 
<br/> But if a is something else:
- `a.copy()` will return the **same type as `a` or fail** depending on its type.
- `np.copy(a)` will **always** return `numpy.array`.
<br/>

Both methods have an additional order argument defining the memory order in the copy with different default values:
- In `np.copy` it is 'K', which means "Use the order as close to the original as possible". 
- In `ndarray.copy` it is 'C' (Use C order).

## 9. Sorting Arrays

In [147]:
a = np.array([1, 3, 2])
c = np.array([[(1.5, 2, 3), (6, 5, 8)], [(3, 2, 1), (9, 0.5, 6)]], 
                 dtype = float)

In [148]:
a.sort()
a

array([1, 2, 3])

In [149]:
c.sort()
c

array([[[1.5, 2. , 3. ],
        [5. , 6. , 8. ]],

       [[1. , 2. , 3. ],
        [0.5, 6. , 9. ]]])

In [150]:
c.sort(axis = 0)
c

array([[[1. , 2. , 3. ],
        [0.5, 6. , 8. ]],

       [[1.5, 2. , 3. ],
        [5. , 6. , 9. ]]])

In [151]:
c.sort(axis = 1)
c

array([[[0.5, 2. , 3. ],
        [1. , 6. , 8. ]],

       [[1.5, 2. , 3. ],
        [5. , 6. , 9. ]]])

## 10. Subsetting, Slicing, Indexing

In [158]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], 
                 dtype = float)

### Subsetting

In [159]:
a[2]

3

In [160]:
b[1, 2]

6.0

### Slicing

In [162]:
a[0:2] # a[0] and a[1]

array([1, 2])

In [163]:
b[:1] # row 0 of b

array([[1.5, 2. , 3. ]])

In [157]:
c[1, ...] # depth1 of c

array([[3., 2., 1.],
       [4., 5., 6.]])

In [164]:
a[::-1] # inverse a

array([3, 2, 1])

### Boolean Indexing

In [165]:
a[a < 3] # Select elements from a less than 2

array([1, 2])

### Fancy Indexing

In [171]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [172]:
# Select elements (1,0),(0,1),(1,2) and (0,0)
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [173]:
# Select a subset of the matrix’s rows and columns
b[[1, 0, 1, 0]][:, [0, 1, 2, 0]] 

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## 11. Array Manipulation

## Transposing Array

In linear algebra, the **transpose of a matrix** is an operator which **flips a matrix over its diagonal**, that is it switches the row and column indices of the matrix by producing another matrix denoted as $A^T$.

In [174]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
i = np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [175]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

##  Changing Array Shape

In [176]:
# Flatten the array
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

**flatten vs ravel:**
<br/> https://stackoverflow.com/questions/28930465/what-is-the-difference-between-flatten-and-ravel-functions-in-numpy
- `flatten` always returns a copy.
- `ravel` returns a view of the original array whenever possible. This isn't visible in the printed output, but if you modify the array returned by `ravel`, it may modify the entries in the original array. If you modify the entries in an array returned from flatten this will never happen. ravel will often be faster since no memory is copied, but you have to be more careful about modifying the array it returns.
- `reshape((-1,))` gets a view whenever the strides of the array allow it even if that means you don't always get a contiguous array.

In [178]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
g = a - b 
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [186]:
# Reshape, but don’t change data
g.reshape(3, -2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

##  Adding/Removing Elements

In [187]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
g = a - b 
h = a.view() 
h

array([1, 2, 3])

In [189]:
np.resize(h, (2, 6)) 

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [191]:
np.append(h, g)

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [192]:
np.insert(a, 1, 5) 

array([1, 5, 2, 3])

In [193]:
np.delete(a, [1])

array([1, 3])

##  Combining Arrays

In [194]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
d = np.arange(10, 25 , 5)

In [204]:
a

array([1, 2, 3])

In [205]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [206]:
d

array([10, 15, 20])

In [207]:
# Concatenate arrays
np.concatenate((a, d), axis = 0)

array([ 1,  2,  3, 10, 15, 20])

In [211]:
np.concatenate((a, d))

array([ 1,  2,  3, 10, 15, 20])

In [209]:
# Stack arrays vertically (row-wise)
np.vstack((a,b)) 

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [212]:
e = np.full((2, 2), 7)
f = np.eye(2) 
np.r_[e, f]

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [213]:
# Stack arrays horizontally (column-wise)
np.hstack((e, f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [215]:
# Create stacked column-wise arrays
np.column_stack((a, d)) 

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [216]:
# Create stacked column-wise arrays
np.c_[a, d] 

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

## Splitting Arrays

In [217]:
# Split the array horizontally at the 3rd index
np.hsplit(a, 3) 

[array([1]), array([2]), array([3])]

In [224]:
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (-1, 7, 6)]], 
                 dtype = float)

# Split the array vertically at the 2nd index
np.vsplit(c, 2) 

[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]), array([[[ 3.,  2.,  1.],
         [-1.,  7.,  6.]]])]