## 1. Intro
The NumPy library is the core library for scientific computing in  Python. It provides a high-performance multidimensional array  object, and tools for working with these arrays. 
<br/> Use the following import convention:
```Python
import numpy as np
```

<img src="./Screenshots/NumPy_01.PNG">

3D array:
<br/>https://stackoverflow.com/questions/22981845/3-dimensional-array-in-numpy

## 2. Creating Arrays

In [2]:
import numpy as np

np.array([1, 2, 3])

array([1, 2, 3])

In [55]:
np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [56]:
np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], 
             dtype = float)

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### Initial Placeholders

In [6]:
# Create an array of zeros
np.zeros((3, 4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
# Create an array of ones
d = np.ones((2, 3, 4), dtype = np.int16)
d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
# Create an array of evenly spaced values (step value)  
np.arange(10, 25, 3)

array([10, 13, 16, 19, 22])

In [12]:
# Create an array of evenly spaced values (number of samples)
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [49]:
# Create a constant array
e = np.full((2, 3), 7)
e

array([[7, 7, 7],
       [7, 7, 7]])

In [50]:
# Create a 2X2 identity matrix
f = np.eye(5, dtype = np.int16)
f

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [31]:
# Create an array with random values
np.random.random((2, 3))  

array([[0.46290585, 0.94603626, 0.92978797],
       [0.04997772, 0.91578375, 0.29259375]])

In [34]:
# Create an empty array
# Return a new array of given shape and type, 
# without initializing entries.
np.empty((3, 4))  

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3. I/O

### Saving & Loading On Disk

In [36]:
np.save('my_array', a)

In [37]:
np.savez('array.npz', a, b)

In [41]:
np.load('my_array.npy')

array([1, 2, 3])

In [42]:
np.load('array.npz')

### Saving & Loading Text Files

```Python
np.loadtxt("myfile.txt")
np.genfromtxt("my_file.csv", delimiter=',')
np.savetxt("myarray.txt", a, delimiter=" ")
```

## 4. Data Types

- **np.intZZ**: Signed ZZ-bit integer types (ZZ = 16, 32, 64, default int32)
- **np.float32**: Standard double-precision floating point
- **np.complex**: Complex numbers represented by 128 floats
- **np.bool**: Boolean type storing TRUE and FALSE values
- **np.object**: Python object type
- **np.string_**: Fixed-length string type
- **np.unicode_**: Fixed-length unicode type

## 5 . Inspecting Your Array

In [69]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], 
                 dtype = float)

### Array dimensions

In [82]:
a.shape

(3,)

In [83]:
b.shape

(2, 3)

In [84]:
c.shape

(2, 2, 3)

### Length of array: return X dimension

In [85]:
len(a)

3

In [86]:
len(b)

2

In [87]:
len(c)

2

### Number of array dimensions

In [88]:
a.ndim

1

In [89]:
b.ndim

2

In [90]:
c.ndim

3

### Data type of array elements

In [91]:
a.dtype

dtype('int32')

In [92]:
b.dtype

dtype('float64')

In [93]:
c.dtype

dtype('float64')

### Name of data type

In [94]:
a.dtype.name

'int32'

In [95]:
b.dtype.name

'float64'

In [96]:
c.dtype.name

'float64'

### Convert an array to a different type

In [97]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
c.astype(int)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [4, 5, 6]]])

## 6. Asking For Help

In [99]:
 np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## 7. Array Mathematics

### Arithmetic Operations

In [100]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)

In [103]:
# Subtraction
g = a - b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [104]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [105]:
# Addition
a + b

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [106]:
np.add(a, b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [107]:
# Division
a / b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [108]:
np.divide(a, b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [109]:
#  Multiplication
a * b  

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [110]:
np.multiply(a, b) 

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [114]:
# Exponentiation
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [120]:
# Square root
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [121]:
# Print sines of an array
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [122]:
# Element-wise cosine
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [123]:
# Element-wise natural logarithm
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [125]:
# Dot product
e = np.full((2,2),7)
f = np.eye(2)  

e.dot(f)

array([[7., 7.],
       [7., 7.]])

### Comparison

In [126]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)

In [127]:
a == b  

array([[False,  True,  True],
       [False, False, False]])

In [128]:
a < 2

array([ True, False, False])

In [129]:
np.array_equal(a, b)

False

### Aggregate Functions

In [148]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (6, 1, 5)], dtype = float)

In [149]:
a.sum() 

6

In [150]:
a.min()

1

In [151]:
b.max(axis = 0)

array([6., 2., 5.])

In [152]:
b.max(axis = 1)

array([3., 6.])

In [154]:
# Cumulative sum of the elements
b.cumsum(axis = 1) 

array([[ 1.5,  3.5,  6.5],
       [ 6. ,  7. , 12. ]])

In [155]:
b.cumsum(axis = 0) 

array([[1.5, 2. , 3. ],
       [7.5, 3. , 8. ]])

In [163]:
a.mean()

2.0

In [164]:
np.median(b)

2.5

In [165]:
# Correlation coefficient
np.corrcoef(a) 

1.0

In [166]:
# Standard deviation
np.std(b)

1.8352262954621033

## 8. Copying Arrays

In [167]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (6, 1, 5)], dtype = float)

In [171]:
# Create a view of the array with the same data
h = a.view() 
h

array([1, 2, 3])

In [172]:
# Create a copy of the array
np.copy(a)

array([1, 2, 3])

In [ ]:
# Create a deep copy of the array
h = a.copy()

**np.copy() vs `=`**

In [174]:
x = np.array([1, 2, 3])
y = x
y

array([1, 2, 3])

In [175]:
z = np.copy(x)
z

array([1, 2, 3])

Note that, when we modify x, y changes, but not z:

In [176]:
x[0] = 10
x[0] == y[0]

True

In [177]:
x[0] == z[0]

False

**np.copy() vs ndarray.copy()**

https://stackoverflow.com/questions/56028405/difference-between-array-copy-vs-numpy-copyarray

## 9. Sorting Arrays

In [186]:
a = np.array([1, 3, 2])
c = np.array([[(1.5, 2, 3), (6, 5, 8)], [(3, 2, 1), (9, 0.5, 6)]], 
                 dtype = float)

In [187]:
a.sort()
a

array([1, 2, 3])

In [188]:
c.sort()
c

array([[[1.5, 2. , 3. ],
        [5. , 6. , 8. ]],

       [[1. , 2. , 3. ],
        [0.5, 6. , 9. ]]])

In [192]:
c.sort(axis = 0)
c

array([[[0.5, 2. , 3. ],
        [1. , 6. , 8. ]],

       [[1.5, 2. , 3. ],
        [5. , 6. , 9. ]]])

In [190]:
c.sort(axis = 1)
c

array([[[0.5, 2. , 3. ],
        [1. , 6. , 8. ]],

       [[1.5, 2. , 3. ],
        [5. , 6. , 9. ]]])

## 10. Subsetting, Slicing, Indexing

In [3]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], 
                 dtype = float)

### Subsetting

In [5]:
a[2]

3

In [6]:
b[1, 2]

6.0

### Slicing

In [7]:
a[0:2]

array([1, 2])

In [9]:
b[:1]

array([[1.5, 2. , 3. ]])

In [10]:
c[1, ...]

array([[3., 2., 1.],
       [4., 5., 6.]])

In [11]:
a[::-1]

array([3, 2, 1])

### Boolean Indexing

In [13]:
a[a < 3] # Select elements from a less than 2

array([1, 2])

### Fancy Indexing

In [16]:
# Select elements (1,0),(0,1),(1,2) and (0,0)
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [18]:
# Select a subset of the matrix’s rows and columns
b[[1, 0, 1, 0]][:,[0,1,2,0]] 

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## 11. Array Manipulation

## Tranposing Array

In [20]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
i = np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [21]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

##  Changing Array Shape

In [26]:
# Flatten the array
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [28]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
g = a - b 
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [29]:
# Reshape, but don’t change data
g.reshape(3, -2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

##  Adding/Removing Elements

In [38]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
g = a - b 
h = a.view() 
h

array([1, 2, 3])

In [39]:
np.resize(h, (2,6)) 

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [40]:
np.append(h,g)

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [43]:
np.insert(a, 1, 5) 

array([1, 5, 2, 3])

In [45]:
np.delete(a, [1])

array([1, 3])

##  Combining Arrays

In [48]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
d = np.arange(10, 25 , 5)

In [47]:
# Concatenate arrays
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [49]:
# Stack arrays vertically (row-wise)
np.vstack((a,b)) 

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [51]:
e = np.full((2,2),7)
f = np.eye(2) 
np.r_[e, f]

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [53]:
# Stack arrays horizontally (column-wise)
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [54]:
#  Create stacked column-wise arrays
np.column_stack((a,d)) 

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [56]:
# Create stacked column-wise arrays
np.c_[a, d] 

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

## Splitting Arrays

In [57]:
# Split the array horizontally at the 3rd index
np.hsplit(a,3) 

[array([1]), array([2]), array([3])]

In [61]:
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], 
                 dtype = float)

# Split the array vertically at the 2nd index
np.vsplit(c, 2) 

[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 1.],
         [4., 5., 6.]]])]