## 1. Intro
The NumPy library is the core library for scientific computing in  Python. It provides a high-performance multidimensional array  object, and tools for working with these arrays. 
<br/> Use the following import convention:
```Python
import numpy as np
```

## 2. Creating Arrays

In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], 
             dtype = float)

### Initial Placeholders

In [6]:
# Create an array of zeros
np.zeros((3, 4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# Create an array of ones
np.ones((2, 3, 4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
# Create an array of evenly spaced values (step value)  
np.arange(10, 25, 3)

array([10, 13, 16, 19, 22])

In [12]:
# Create an array of evenly spaced values (number of samples)
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [15]:
# Create a constant array
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [19]:
# Create a 2X2 identity matrix
np.eye(2, dtype = np.int16)

array([[1, 0],
       [0, 1]], dtype=int16)

In [31]:
# Create an array with random values
np.random.random((2, 3))  

array([[0.46290585, 0.94603626, 0.92978797],
       [0.04997772, 0.91578375, 0.29259375]])

In [34]:
# Create an empty array
# Return a new array of given shape and type, 
# without initializing entries.
np.empty((3, 4))  

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3. I/O

### Saving & Loading On Disk

In [35]:
np.save('my_array', a)