## 1. Intro
The `SciPy` library is one of the core packages for  scientific computing that provides mathematical  algorithms and convenience functions built on the NumPy extension of Python.

## 2. Interacting With NumPy

In [1]:
import numpy as np
import scipy as sp
a = np.array([1, 2, 3])
b = np.array([(1 + 5j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]])

### Index Tricks

In [2]:
# Create a dense meshgrid
np.mgrid[0:5, 0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [3]:
# Create an open meshgrid
np.ogrid[0:2, 0:2] 

[array([[0],
        [1]]), array([[0, 1]])]

In [4]:
# Stack arrays vertically (row-wise)
np.r_[3, [0]*5, -1:1:10j]

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,
        1.        ])

In [5]:
# Create stacked column-wise arrays 
a1 = np.array([6, 1, 2])
np.c_[a, a1]

array([[1, 6],
       [2, 1],
       [3, 2]])

### Shape Manipulation

In [6]:
# Permute array dimensions 
np.transpose(b)           

array([[1.+5.j, 0.+4.j],
       [0.+2.j, 0.+5.j],
       [0.+3.j, 0.+6.j]])

In [7]:
# Flatten the array
b.flatten()                

array([1.+5.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j])

In [8]:
# Stack arrays horizontally (column-wise)
np.hstack((a, a1))          

array([1, 2, 3, 6, 1, 2])

In [9]:
# Stack arrays vertically (row-wise)
np.vstack((a, b)) 

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [1.+5.j, 0.+2.j, 0.+3.j],
       [0.+4.j, 0.+5.j, 0.+6.j]])

In [10]:
# Split the array horizontally at the 2nd index
np.hsplit(c, 2) 

[array([[[1.5, 2. , 3. ]],
 
        [[3. , 2. , 1. ]]]), array([[[4., 5., 6.]],
 
        [[4., 5., 6.]]])]

In [11]:
# Split the array vertically at the 2nd index
np.vsplit(c, 2)

[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 1.],
         [4., 5., 6.]]])]

### Polynomials

In [12]:
from numpy import poly1d

# Create a polynomial object
p = poly1d([3,4,5]) 
p

poly1d([3, 4, 5])

### Vectorizing Functions

In [13]:
def myfunc(a):
    if a < 0: 
        return a*2
    else:
        return a/2
    
np.vectorize(myfunc) 

### Type Handling 

In [14]:
# Return the real part of the array elements
np.real(c)

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [15]:
# Return the imaginary part of the array elements
np.imag(c)

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
# Return a real array if complex parts close to 0
np.real_if_close(c, tol=1000)

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [17]:
# Cast object to a data type
np.cast['f'](np.pi)

array(3.1415927, dtype=float32)

### Other Useful Functions

In [18]:
# Return the angle of the complex argument
np.angle(b, deg=True)

array([[78.69006753, 90.        , 90.        ],
       [90.        , 90.        , 90.        ]])

In [19]:
# Create an array of evenly spaced values (number of samples)
g = np.linspace(0, np.pi, num = 5)
g

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [20]:
g[3:] += np.pi
g

array([0.        , 0.78539816, 1.57079633, 5.49778714, 6.28318531])

In [21]:
# Unwrap 
np.unwrap(g)

array([ 0.        ,  0.78539816,  1.57079633, -0.78539816,  0.        ])

In [22]:
# Create an array of evenly spaced values  (log scale)
np.logspace(0, 10, 3)

array([1.e+00, 1.e+05, 1.e+10])

In [23]:
# Return values from a list of arrays depending on conditions
np.select([c<4], [c*2])

array([[[3., 4., 6.],
        [0., 0., 0.]],

       [[6., 4., 2.],
        [0., 0., 0.]]])

In [24]:
# Factorial
from scipy import special, misc

special.factorial(a)

array([1., 2., 6.])

From scipy 1.0, use `special` for `factorial`:
https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.factorial.html

In [25]:
# Combine N things taken at k time
special.comb(10, 3, exact=True)

120

In [26]:
# Weights for Np-point central derivative
misc.central_diff_weights(3)

array([-0.5,  0. ,  0.5])

In [27]:
# Find the n-th derivative of a function at a point
misc.derivative(myfunc, 1.0)

0.5

## 3. Linear Algebra
- Use the **`linalg`** and **`sparse`** modules. 
- Note that **`scipy.linalg`** contains and expands on  **`numpy.linalg`**. 
- Array vs Matrix: https://stackoverflow.com/questions/4151128/what-are-the-differences-between-numpy-arrays-and-matrices-which-one-should-i-u

In [28]:
from scipy import linalg, sparse

### Creating Matrices

In [29]:
b = np.array([(1 + 5j, 2j, 3j), (4j, 5j, 6j)])

A = np.matrix(np.random.random((2, 2)))
B = np.asmatrix(b)
# Unlike matrix, asmatrix does not make a copy 
# if the input is already a matrix or an ndarray. 
# Equivalent to matrix(data, copy=False).
C = np.mat(np.random.random((10, 5)))
D = np.mat([[3, 4], [5, 6]])

In [30]:
A

matrix([[0.18232937, 0.28223918],
        [0.89339543, 0.18830253]])

In [31]:
B

matrix([[1.+5.j, 0.+2.j, 0.+3.j],
        [0.+4.j, 0.+5.j, 0.+6.j]])

In [32]:
C

matrix([[0.5433112 , 0.74478276, 0.71448065, 0.52126514, 0.51940335],
        [0.04043918, 0.23762696, 0.08083145, 0.76067833, 0.32753633],
        [0.63302968, 0.44789165, 0.26613907, 0.79309156, 0.3741623 ],
        [0.04163313, 0.33914945, 0.66386606, 0.5574993 , 0.3649906 ],
        [0.79254526, 0.7518772 , 0.04588177, 0.19344784, 0.81813529],
        [0.53812385, 0.88549581, 0.47301097, 0.2017154 , 0.30687798],
        [0.9669992 , 0.68692359, 0.71231404, 0.97409973, 0.24052118],
        [0.25814788, 0.69141684, 0.99795064, 0.24849061, 0.51481654],
        [0.80036805, 0.69526852, 0.07063485, 0.46277153, 0.00993205],
        [0.9240375 , 0.41105873, 0.75755574, 0.40490018, 0.34754774]])

In [33]:
D

matrix([[3, 4],
        [5, 6]])

###  Basic Matrix Routines

####  Inverse

In [34]:
# Inverse
A.I

matrix([[-0.86449439,  1.29575625],
        [ 4.10156636, -0.83707167]])

In [35]:
# Inverse
linalg.inv(A)

array([[-0.86449439,  1.29575625],
       [ 4.10156636, -0.83707167]])

In [36]:
# Tranpose matrix
A.T

matrix([[0.18232937, 0.89339543],
        [0.28223918, 0.18830253]])

In [37]:
# Conjugate transposition
A.H

matrix([[0.18232937, 0.89339543],
        [0.28223918, 0.18830253]])

In [38]:
# Trace
np.trace(A)

0.3706319005092332

### Norm

In [39]:
# Frobenius norm
linalg.norm(A)

0.9728906354958945

In [41]:
# L1 norm (max column sum)
linalg.norm(A, 1)

1.0757247977069433

In [42]:
# L inf norm (max row sum)
linalg.norm(A,np.inf)

1.081697961751799

###  Rank

In [45]:
# Matrix rank
np.linalg.matrix_rank(C)   

5

## 4. Asking for Help